name: webpage
description: My website for landing and experiments
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  logging: ^1.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/background.glsl